=== lolo8304/BusinessDecisionVerify/business-decision-verify/input/fachbegriff_element_mapping_v0.1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2015 rel. 3 sp1 (http://www.altova.com) by AXA Tech (AXA Technology Services) -->
<!--  
Fachbegriff-Element-Mapping für Decision Model

basierend auf dem Modell Business Decision Version x.y by Wilfried Kurth, C723649

letzte Änderungen Version 1:
- 13.07.2015: initial Version,  (Wilfried Kurth, C723649)

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:element name="ConceptElementMapping" type="CT_ConceptElementMapping"/>
	<xs:complexType name="CT_ConceptElementMapping">
		<xs:sequence>
			<xs:element name="decisionId" type="DecisionId" minOccurs="1"/>
			<xs:element name="ConceptElement" type="CT_ConceptElement" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CT_ConceptElement">
		<xs:sequence>
			<xs:element name="businessObject" type="xs:string" minOccurs="1"/>
			<xs:element name="factTypeName" type="xs:string" minOccurs="1"/>
			<xs:element name="variableName" type="xs:string" minOccurs="1"/>
			<xs:element name="businessConcept" type="xs:string" minOccurs="1"/>
			<xs:element name="attributeName" type="xs:string" minOccurs="1"/>
			<xs:element name="domainKey" type="DomainKeyCode" minOccurs="1"/>
			<xs:element name="CodeNaming" type="CT_CodeNaming" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CT_CodeNaming">
		<xs:sequence>
			<xs:element name="code" type="xs:string" minOccurs="1"/>
			<xs:element name="naming" type="xs:string" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="DecisionId">
		<xs:restriction base="xs:string">
			<xs:pattern value="BD[0-9]{4}_[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DomainKeyCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CHAR"/>
			<xs:enumeration value="CHAR_LONG"/>
			<xs:enumeration value="CHAR_DATE"/>
			<xs:enumeration value="CHAR_TIME"/>
			<xs:enumeration value="CHAR_TMSTP"/>
			<xs:enumeration value="SMALLINT"/>
			<xs:enumeration value="INTEGER"/>
			<xs:enumeration value="BIGINT"/>
			<xs:enumeration value="DECIMAL"/>
			<xs:enumeration value="FLOAT_SNGL"/>
			<xs:enumeration value="FLOAT_DBL"/>
			<xs:enumeration value="BOOLEAN"/>
			<xs:enumeration value="OCTET"/>
			<xs:enumeration value="OCTET_LONG"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== lolo8304/BusinessDecisionVerify/business-decision-verify/input/FEM0010_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConceptElementMapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fachbegriff_element_mapping_v0.1.xsd">
	<decisionId>BD0010_001</decisionId>
	<ConceptElement>
		<businessObject>Versand</businessObject>
		<factTypeName>Versandart-Fragebogen</factTypeName>
		<variableName>VERSAND_ART_CDOMS_FRAGEBOGEN</variableName>
		<businessConcept>Versand</businessConcept>
		<attributeName>vsndArtCdomsFrgbgn</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>eMail</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>Post</naming>
		</CodeNaming>
		<CodeNaming>
			<code>3</code>
			<naming>persönlich</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Fragebogen</businessObject>
		<factTypeName>Liste Interview-Frage</factTypeName>
		<variableName>ARRAY_INTERVIEW_FRAGE</variableName>
		<businessConcept>Fragebogen</businessConcept>
		<attributeName>intervFrage</attributeName>
		<domainKey>SMALLINT</domainKey>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Person</businessObject>
		<factTypeName>Beruf</factTypeName>
		<variableName>BERUF_CDGPD</variableName>
		<businessConcept>Person</businessConcept>
		<attributeName>brufCdgpd</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>Consultant</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>Controller</naming>
		</CodeNaming>
		<CodeNaming>
			<code>3</code>
			<naming>Gärtner</naming>
		</CodeNaming>
		<CodeNaming>
			<code>4</code>
			<naming>Handwerker</naming>
		</CodeNaming>
		<CodeNaming>
			<code>5</code>
			<naming>Verkäufer</naming>
		</CodeNaming>
		<CodeNaming>
			<code>6</code>
			<naming>Vertreter</naming>
		</CodeNaming>
	</ConceptElement>
</ConceptElementMapping>

=== lolo8304/BusinessDecisionVerify/business-decision-verify/input/FEM0007_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConceptElementMapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fachbegriff_element_mapping_v0.1.xsd">
	<decisionId>BD0007_001</decisionId>
	<ConceptElement>
		<businessObject>Kredit</businessObject>
		<factTypeName>Ausfallwahrscheinlichkeit</factTypeName>
		<variableName>AUSFALL_WAHRSCHEINLICHKEIT_CDKR</variableName>
		<businessConcept>Kredit</businessConcept>
		<attributeName>ausflWhrschktCdkr</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>hoch</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>mittel</naming>
		</CodeNaming>
		<CodeNaming>
			<code>3</code>
			<naming>gering</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Antragsteller</businessObject>
		<factTypeName>Beschäftigungssituation</factTypeName>
		<variableName>BESCHAEFTIGUNG_ZUSTAND_CDKR</variableName>
		<businessConcept>AntragSteller</businessConcept>
		<attributeName>bschaeftgZustCdkr</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>gut</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>mittel</naming>
		</CodeNaming>
		<CodeNaming>
			<code>3</code>
			<naming>schlecht</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Antragsteller</businessObject>
		<factTypeName>Kreditbelastung</factTypeName>
		<variableName>KREDIT_BELASTUNG_CDKR</variableName>
		<businessConcept>AntragSteller</businessConcept>
		<attributeName>krdtBlastgCdkr</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>hoch</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>mittel</naming>
		</CodeNaming>
		<CodeNaming>
			<code>3</code>
			<naming>gering</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Antragsteller</businessObject>
		<factTypeName>Hypothekenbelastung</factTypeName>
		<variableName>HYPOTHEK_BELASTUNG_CDKR</variableName>
		<businessConcept>AntragSteller</businessConcept>
		<attributeName>hyptkBlastgCdkr</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>hoch</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>gering</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Kreditbelastung</businessObject>
		<factTypeName>Studentenkredit</factTypeName>
		<variableName>STUDENT_KREDIT_HOEHE_CDKR</variableName>
		<businessConcept>KreditBelastung</businessConcept>
		<attributeName>studtKrdtHoeheCdkr</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>hoch</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>niedrig</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Kreditbelastung</businessObject>
		<factTypeName>Konsumkredit</factTypeName>
		<variableName>KONSUM_KREDIT_HOEHE_CDKR</variableName>
		<businessConcept>KreditBelastung</businessConcept>
		<attributeName>konsumKrdtHoeheCdkr</attributeName>
		<domainKey>SMALLINT</domainKey>
		<CodeNaming>
			<code>1</code>
			<naming>hoch</naming>
		</CodeNaming>
		<CodeNaming>
			<code>2</code>
			<naming>mittel</naming>
		</CodeNaming>		
		<CodeNaming>
			<code>3</code>
			<naming>niedrig</naming>
		</CodeNaming>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Beschäftigungssitution</businessObject>
		<factTypeName>Anzahl Jahre aktueller Job</factTypeName>
		<variableName>ANZAHL_JAHR_IN_JOB_AKTUELL</variableName>
		<businessConcept>BeschaeftigungSituation</businessConcept>
		<attributeName>anzJahrJobAktl</attributeName>
		<domainKey>SMALLINT</domainKey>
	</ConceptElement>
	<ConceptElement>
		<businessObject>Beschäftigungssitution</businessObject>
		<factTypeName>Anzahl Jobs letzte 5 Jahre</factTypeName>
		<variableName>ANZAHL_JOB_IN_5_JAHR</variableName>
		<businessConcept>BeschaeftigungSituation</businessConcept>
		<attributeName>anzJobIn5Jahr</attributeName>
		<domainKey>SMALLINT</domainKey>
	</ConceptElement>
</ConceptElementMapping>

=== lolo8304/BusinessDecisionVerify/business-decision-verify/input/FEM0020_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConceptElementMapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fachbegriff_element_mapping_v0.1.xsd">
  <decisionId>BD0020_001</decisionId>
  <ConceptElement>
      <businessObject>Fahrer</businessObject>
      <factTypeName>Aussetzung Fahrerlaubnis</factTypeName>
      <variableName>AUSSETZUNG_FAHR_ERLAUBNIS_CDMF</variableName>
      <businessConcept>Fahrer</businessConcept>
      <attributeName>austzgFahrErlaubCdmf</attributeName>
      <domainKey>SMALLINT</domainKey>
        <CodeNaming>
          <code>1</code>
          <naming>erforderlich</naming>
        </CodeNaming>
        <CodeNaming>
          <code>2</code>
          <naming>empfohlen</naming>
        </CodeNaming>
        <CodeNaming>
          <code>3</code>
          <naming>nicht erforderlich</naming>
        </CodeNaming>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Physis-Test</businessObject>
      <factTypeName>Alter Reaktionstest in Monaten</factTypeName>
      <variableName>ALTER_REAKTION_TEST_IN_MONAT</variableName>
      <businessConcept>PhysisTest</businessConcept>
      <attributeName>alterReaktnTestInMonat</attributeName>
      <domainKey>SMALLINT</domainKey>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Physis-Test</businessObject>
      <factTypeName>Aktualit&#228;t Reaktionstest</factTypeName>
      <variableName>AKTUALITAET_REAKTION_TEST_CDMF</variableName>
      <businessConcept>PhysisTest</businessConcept>
      <attributeName>aktlttReaktnTestCdmf</attributeName>
      <domainKey>SMALLINT</domainKey>
        <CodeNaming>
          <code>1</code>
          <naming>abgelaufen</naming>
        </CodeNaming>
        <CodeNaming>
          <code>2</code>
          <naming>veraltet</naming>
        </CodeNaming>
        <CodeNaming>
          <code>3</code>
          <naming>aktuell</naming>
        </CodeNaming>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Physis-Test</businessObject>
      <factTypeName>Alter Sehtest in Monaten</factTypeName>
      <variableName>ALTER_SEH_TEST_IN_MONAT</variableName>
      <businessConcept>PhysisTest</businessConcept>
      <attributeName>alterSehTestInMonat</attributeName>
      <domainKey>SMALLINT</domainKey>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Physis-Test</businessObject>
      <factTypeName>Aktualit&#228;t Sehtest</factTypeName>
      <variableName>AKTUALITAET_SEH_TEST_CDMF</variableName>
      <businessConcept>PhysisTest</businessConcept>
      <attributeName>aktlttSehTestCdmf</attributeName>
      <domainKey>SMALLINT</domainKey>
        <CodeNaming>
          <code>1</code>
          <naming>abgelaufen</naming>
        </CodeNaming>
        <CodeNaming>
          <code>2</code>
          <naming>veraltet</naming>
        </CodeNaming>
        <CodeNaming>
          <code>3</code>
          <naming>aktuell</naming>
        </CodeNaming>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Physis-Test</businessObject>
      <factTypeName>Test Physis</factTypeName>
      <variableName>TEST_PHYSIS_CDMF</variableName>
      <businessConcept>PhysisTest</businessConcept>
      <attributeName>testPhysisCdmf</attributeName>
      <domainKey>SMALLINT</domainKey>
        <CodeNaming>
          <code>1</code>
          <naming>erforderlich</naming>
        </CodeNaming>
        <CodeNaming>
          <code>2</code>
          <naming>empfohlen</naming>
        </CodeNaming>
        <CodeNaming>
          <code>3</code>
          <naming>nicht erforderlich</naming>
        </CodeNaming>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Psycho-Test</businessObject>
      <factTypeName>Anzahl Verkehrsverst&#246;sse letzte 12 Monate</factTypeName>
      <variableName>ANZAHL_VERKEHR_VERSTOSS_IN_12_MONAT</variableName>
      <businessConcept>PsychoTest</businessConcept>
      <attributeName>anzVkehrVstssIn12Monat</attributeName>
      <domainKey>SMALLINT</domainKey>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Psycho-Test</businessObject>
      <factTypeName>inkl. schwere Verkehrsverst&#246;sse</factTypeName>
      <variableName>KZ_VERKEHR_VERSTOSS_SCHWER_INKLUSIV</variableName>
      <businessConcept>PsychoTest</businessConcept>
      <attributeName>kzVkehrVstssSchwerInkl</attributeName>
      <domainKey>SMALLINT</domainKey>      
        <CodeNaming>
          <code>0</code>
          <naming>nein</naming>
        </CodeNaming>
        <CodeNaming>
          <code>1</code>
          <naming>ja</naming>
        </CodeNaming>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Psycho-Test</businessObject>
      <factTypeName>Bewertung Fahrverhalten</factTypeName>
      <variableName>BEWERTUNG_FAHR_VERHALTEN_CDMF</variableName>
      <businessConcept>PsychoTest</businessConcept>
      <attributeName>bwrtgFahrVhltnCdmf</attributeName>
      <domainKey>SMALLINT</domainKey>
        <CodeNaming>
          <code>1</code>
          <naming>gef&#228;hrlich</naming>
        </CodeNaming>
        <CodeNaming>
          <code>2</code>
          <naming>auff&#228;llig</naming>
        </CodeNaming>
        <CodeNaming>
          <code>3</code>
          <naming>ok</naming>
        </CodeNaming>
      </ConceptElement>
  <ConceptElement>
      <businessObject>Psycho-Test</businessObject>
      <factTypeName>Test Psyche</factTypeName>
      <variableName>TEST_PSYCHE_CDMF</variableName>
      <businessConcept>PsychoTest</businessConcept>
      <attributeName>testPsycheCdmf</attributeName>
      <domainKey>SMALLINT</domainKey>
        <CodeNaming>
          <code>1</code>
          <naming>erforderlich</naming>
        </CodeNaming>
        <CodeNaming>
          <code>2</code>
          <naming>empfohlen</naming>
        </CodeNaming>
        <CodeNaming>
          <code>3</code>
          <naming>nicht erforderlich</naming>
        </CodeNaming>
      </ConceptElement>
</ConceptElementMapping>
